name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.dckr_pat_mBhknDnZQ4bVGy1h8IKy238uJY0 }}" | docker login -u "${{ secrets.chipln }}" --password-stdin

      - name: Build image
        run: docker build -t chipln/docker101tutorial:latest .

      - name: Push image
        run: docker push chipln/docker101tutorial:latest
